# Generated by Django 5.0 on 2024-04-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=300)),
                ('Masul', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomi', models.CharField(max_length=300)),
                ('Masul', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=300)),
                ('Familyasi', models.CharField(max_length=300)),
                ('horida', models.CharField(choices=[('tugallanmagan', 'tugallanmagan'), ('tugallangan', 'tugallangan')], max_length=15, verbose_name='Status')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.maktab')),
            ],
        ),
        migrations.AddField(
            model_name='maktab',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.tuman'),
        ),
    ]
