# Generated by Django 5.0 on 2024-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaxs',
            name='horida',
            field=models.CharField(choices=[('tugallangan', 'tugallangan'), ('tugallanmagan', 'tugallanmagan')], max_length=15, verbose_name='Status'),
        ),
    ]
